name: Release

on:
  push:
    branches:
      - main
      - next
      - next-major
      - alpha
      - beta

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command

      - name: store generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "**CI** Apply built files"
          file_pattern: dist/**
          add_options: '-u'

      - name: create dist.zip
        uses: montudor/action-zip@v1
        with:
          args: zip -r dist.zip dist
      
      - name: Semantic Release
        run: npx semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
