name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '5 * * * *'
    # scheduled for every hour

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: upstream             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: alainbryden/bitburner-scripts      # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: upstream          # set the branch to merge to
